DROP TABLE IF EXISTS flyway_schema_history cascade;
DROP TABLE IF EXISTS TB_TIPO_PESSOA CASCADE;
DROP TABLE IF EXISTS TB_PESSOA CASCADE;
DROP TABLE IF EXISTS TB_TIPO_LANCAMENTO CASCADE;
DROP TABLE IF EXISTS TB_PRODUTO_SERVICO CASCADE;
DROP TABLE IF EXISTS TB_LANCAMENTO CASCADE;
DROP TABLE IF EXISTS TB_LANCAMENTO_PRODUTO_SERVICO CASCADE;
DROP TABLE IF EXISTS TB_CONTA_BANCARIA CASCADE;
DROP TABLE IF EXISTS TB_FORMA_PAGAMENTO CASCADE;
DROP TABLE IF EXISTS TB_PAGAMENTO CASCADE;
DROP TABLE IF EXISTS TB_PARCELAMENTO CASCADE;
DROP TABLE IF EXISTS TB_LANCAMENTO_PAGAMENTO CASCADE;
DROP TABLE IF EXISTS TB_TIPO_PESSOA CASCADE;
DROP TABLE IF EXISTS TB_ARQUIVO CASCADE;
DROP TABLE IF EXISTS TB_LANCAMENTO_ARQUIVO CASCADE;

-- FUNC0001 - GERENCIADOR DE PESSOAS

CREATE TABLE IF NOT EXISTS TB_TIPO_PESSOA (
    CODIGO SERIAL NOT NULL,
    DESCRICAO VARCHAR(85) NOT NULL,
    CONSTRAINT PK_TIPO_PESSOA PRIMARY KEY (CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_PESSOA (
    CODIGO SERIAL NOT NULL,
    ID_TIPO_PESSOA INTEGER not null,
    NOME VARCHAR(85) NOT NULL,
    CONSTRAINT PK_PESSOA PRIMARY KEY (CODIGO),
    CONSTRAINT FK_TIPO_PESSOA FOREIGN KEY (ID_TIPO_PESSOA) REFERENCES TB_TIPO_PESSOA (CODIGO)
);

-- FUNC0002 - GERENCIADOR DE LANCAMENTO FINANCEIRO

CREATE TABLE IF NOT EXISTS TB_TIPO_LANCAMENTO (
    CODIGO SERIAL NOT null,
    IDENTIFICADOR VARCHAR(85) NOT NULL,
    DESCRICAO VARCHAR(85) NOT NULL,
    CONSTRAINT PK_TIPO_LANCAMENTO PRIMARY KEY (CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_PRODUTO_SERVICO (
    CODIGO SERIAL NOT null,
    DESCRICAO VARCHAR(85) NOT NULL,
    CONSTRAINT PK_PRODUTO_SERVICO PRIMARY KEY (CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_LANCAMENTO (
    CODIGO SERIAL NOT NULL,
    ID_PESSOA_FAVORECIDA INTEGER NOT NULL,
    ID_PESSOA_RESPONSAVEL_LANCAMENTO INTEGER NOT NULL,
    ID_TIPO_LANCAMENTO INTEGER NOT NULL,
    IDENTIFICADOR VARCHAR(100) NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL,
    CONSTRAINT PK_LANCAMENTO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_PESSOA_FAVORECIDA FOREIGN KEY (ID_PESSOA_FAVORECIDA) REFERENCES TB_PESSOA(CODIGO),
    CONSTRAINT FK_PESSOA_RESPONSAVEL_LANCAMENTO FOREIGN KEY (ID_PESSOA_RESPONSAVEL_LANCAMENTO) REFERENCES TB_PESSOA(CODIGO),
    CONSTRAINT FK_TIPO_LANCAMENTO FOREIGN KEY (ID_TIPO_LANCAMENTO) REFERENCES TB_TIPO_LANCAMENTO(CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_LANCAMENTO_PRODUTO_SERVICO (
    CODIGO SERIAL NOT NULL,
    ID_LANCAMENTO INTEGER NOT NULL,
    ID_PRODUTO_SERVICO INTEGER NOT NULL,
    VALOR FLOAT NOT NULL,
    CONSTRAINT PK_LANCAMENTO_PRODUTO_SERVICO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_LANCAMENTO FOREIGN KEY (ID_LANCAMENTO) REFERENCES TB_LANCAMENTO(CODIGO),
    CONSTRAINT FK_PRODUTO_SERVICO FOREIGN KEY (ID_PRODUTO_SERVICO) REFERENCES TB_PRODUTO_SERVICO(CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_CONTA_BANCARIA (
    CODIGO SERIAL NOT NULL,
    ID_PESSOA_INSTITUICAO_FINANCEIRA INTEGER NOT NULL,
    ID_PESSOA_TITULAR INTEGER NOT NULL,
    NUMERO VARCHAR(80) NOT NULL,
    DATA_ABERTURA DATE NOT NULL,
    DATA_FECHAMENTO DATE NULL,
    SALDO FLOAT NOT NULL,
    CONSTRAINT PK_CONTA_BANCARIA PRIMARY KEY (CODIGO),
    CONSTRAINT FK_PESSOA_INSTITUICAO_FINANCEIRA FOREIGN KEY (ID_PESSOA_INSTITUICAO_FINANCEIRA) REFERENCES TB_PESSOA(CODIGO),
    CONSTRAINT FK_PESSOA_TITULAR FOREIGN KEY (ID_PESSOA_TITULAR) REFERENCES TB_PESSOA(CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_FORMA_PAGAMENTO (
    CODIGO SERIAL NOT NULL,
    DESCRICAO VARCHAR(85) NOT NULL,
    CONSTRAINT PK_FORMA_PAGAMENTO PRIMARY KEY (CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_PAGAMENTO (
    CODIGO SERIAL NOT NULL,
    ID_CONTA_BANCARIA INTEGER NOT NULL,
    ID_FORMA_PAGAMENTO INTEGER NOT NULL,
    DATA_PAGAMENTO DATE NOT NULL,
    CONSTRAINT PK_PAGAMENTO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_CONTA_BANCARIA FOREIGN KEY (ID_CONTA_BANCARIA) REFERENCES TB_CONTA_BANCARIA(CODIGO),
    CONSTRAINT FK_FORMA_PAGAMENTO FOREIGN KEY (ID_FORMA_PAGAMENTO) REFERENCES TB_FORMA_PAGAMENTO(CODIGO)
);


CREATE TABLE IF NOT EXISTS TB_LANCAMENTO_PAGAMENTO (
    CODIGO SERIAL NOT NULL,
    ID_LANCAMENTO INTEGER NOT NULL,
    ID_PAGAMENTO INTEGER NOT NULL,
    VALOR FLOAT NOT NULL,
    CONSTRAINT PK_LANCAMENTO_PAGAMENTO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_LANCAMENTO FOREIGN KEY (ID_LANCAMENTO) REFERENCES TB_LANCAMENTO(CODIGO),
    CONSTRAINT FK_PAGAMENTO FOREIGN KEY (ID_PAGAMENTO) REFERENCES TB_PAGAMENTO(CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_PARCELAMENTO (
    CODIGO SERIAL NOT NULL,
    ID_PAGAMENTO INTEGER NOT NULL,
    NUMERO INTEGER NOT NULL,
    VALOR FLOAT NOT NULL,
    CONSTRAINT PK_PARCELAMENTO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_PAGAMENTO FOREIGN KEY (ID_PAGAMENTO) REFERENCES TB_PAGAMENTO(CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_PAGAMENTO_PARCELAMENTO (
    CODIGO SERIAL NOT NULL,
    ID_PAGAMENTO INTEGER NOT NULL,
    ID_PARCELAMENTO INTEGER NOT NULL,
    CONSTRAINT PK_PAGAMENTO_PARCELAMENTO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_PAGAMENTO FOREIGN KEY (ID_PAGAMENTO) REFERENCES TB_PAGAMENTO(CODIGO),
    CONSTRAINT FK_PARCELAMENTO FOREIGN KEY (ID_PAGAMENTO) REFERENCES TB_PARCELAMENTO(CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_ARQUIVO (
    CODIGO SERIAL NOT NULL,
    NOME VARCHAR(45) NOT NULL,
    DESCRICAO VARCHAR(80) NULL,
    FORMATO VARCHAR(4) NOT NULL,
    CAMINHO VARCHAR(255) NULL,
    TAMANHO FLOAT NULL,
    DATA_CADASTRO DATE NOT NULL,
    DATA_ATUALIZACAO DATE NOT NULL,
    CONSTRAINT PK_ARQUIVO PRIMARY KEY (CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_LANCAMENTO_ARQUIVO (
    CODIGO SERIAL NOT NULL,
    ID_LANCAMENTO INTEGER NOT NULL,
    ID_ARQUIVO INTEGER NOT NULL,
    CONSTRAINT PK_LANCAMENTO_ARQUIVO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_LANCAMENTO FOREIGN KEY (ID_LANCAMENTO) REFERENCES TB_LANCAMENTO (CODIGO),
    CONSTRAINT FK_ARQUIVO FOREIGN KEY (ID_ARQUIVO) REFERENCES TB_ARQUIVO (CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_TIPO_PERMISSAO_PESSOA (
    CODIGO SERIAL NOT NULL,
    NOME VARCHAR(85) NOT NULL,
    CONSTRAINT PK_TIPO_PERMISSAO_PESSOA PRIMARY KEY (CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_PERMISSAO_PESSOA (
    CODIGO SERIAL NOT NULL,
    ID_PESSOA INTEGER NOT NULL,
    ID_TIPO_PERMISSAO_PESSOA INTEGER NOT NULL,
    CONSTRAINT PK_PERMISSAO_PESSOA PRIMARY KEY (CODIGO),
    CONSTRAINT FK_ID_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA (CODIGO),
    CONSTRAINT FK_TIPO_PERMISSAO_PESSOA FOREIGN KEY (ID_TIPO_PERMISSAO_PESSOA) REFERENCES TB_TIPO_PERMISSAO_PESSOA (CODIGO)
);

DROP TABLE IF EXISTS TB_TIPO_DOCUMENTO CASCADE;
DROP TABLE IF EXISTS TB_DOCUMENTO CASCADE;
DROP TABLE IF EXISTS TB_TIPO_PESSOA CASCADE;
DROP TABLE IF EXISTS TB_PESSOA CASCADE;
DROP TABLE IF EXISTS TB_PESSOA_DOCUMENTO CASCADE;

CREATE TABLE IF NOT EXISTS TB_TIPO_DOCUMENTO (
CODIGO SERIAL NOT NULL,
SIGLA VARCHAR(10) NOT NULL,
DESCRICAO VARCHAR(85) NULL,
CONSTRAINT PK_TIPO_DOCUMENTO PRIMARY KEY (CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_DOCUMENTO (
	CODIGO SERIAL NOT NULL,
	ID_TIPO_DOCUMENTO INTEGER NOT NULL,
	NUMERO VARCHAR(85) NULL,
	DATA_EMISSAO DATE NULL,
	DATA_VENCIMENTO DATE NULL,
	IS_ATIVO BOOLEAN NOT NULL,
	CONSTRAINT PK_DOCUMENTO PRIMARY KEY (CODIGO),
	CONSTRAINT FK_TIPO_DOCUMENTO FOREIGN KEY (ID_TIPO_DOCUMENTO) REFERENCES TB_TIPO_DOCUMENTO (CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_PESSOA_DOCUMENTO (
	CODIGO SERIAL NOT NULL,
	ID_PESSOA INTEGER NOT NULL,
	ID_DOCUMENTO INTEGER NOT NULL,
	CONSTRAINT PK_PESSOA_DOCUMENTO PRIMARY KEY (CODIGO),
	CONSTRAINT FK_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA (CODIGO),
	CONSTRAINT FK_DOCUMENTO FOREIGN KEY (ID_DOCUMENTO) REFERENCES TB_DOCUMENTO (CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_ARQUIVO_DOCUMENTO (
	CODIGO SERIAL NOT NULL,
	ID_ARQUIVO INTEGER NOT NULL,
	ID_DOCUMENTO INTEGER NOT NULL,
	CONSTRAINT PK_ARQUIVO_DOCUMENTO PRIMARY KEY (CODIGO),
	CONSTRAINT FK_ARQUIVO FOREIGN KEY (ID_ARQUIVO) REFERENCES TB_ARQUIVO (CODIGO),
	CONSTRAINT FK_DOCUMENTO FOREIGN KEY (ID_DOCUMENTO) REFERENCES TB_DOCUMENTO (CODIGO)
);

SELECT * FROM TB_DOCUMENTO;

INSERT INTO TB_TIPO_DOCUMENTO (SIGLA, DESCRICAO) VALUES ('CPF', '');
INSERT INTO TB_TIPO_DOCUMENTO (SIGLA, DESCRICAO) VALUES ('CNPJ', '');
INSERT INTO TB_TIPO_DOCUMENTO (SIGLA, DESCRICAO) VALUES ('RG', 'Registro Geral');

INSERT INTO TB_DOCUMENTO (ID_TIPO_DOCUMENTO, NUMERO, DATA_EMISSAO, DATA_VENCIMENTO, IS_ATIVO) VALUES (1, '900.314.640-33', NULL, NULL, TRUE);
INSERT INTO TB_DOCUMENTO (ID_TIPO_DOCUMENTO, NUMERO, DATA_EMISSAO, DATA_VENCIMENTO, IS_ATIVO) VALUES (2, '37.052.988/0001-42', NULL, NULL, TRUE);
INSERT INTO TB_DOCUMENTO (ID_TIPO_DOCUMENTO, NUMERO, DATA_EMISSAO, DATA_VENCIMENTO, IS_ATIVO) VALUES (3, '40.167.943-3', NULL, NULL, TRUE);

INSERT INTO TB_PESSOA_DOCUMENTO (ID_PESSOA, ID_DOCUMENTO) VALUES (1, 1);
INSERT INTO TB_PESSOA_DOCUMENTO (ID_PESSOA, ID_DOCUMENTO) VALUES (2, 2);
INSERT INTO TB_PESSOA_DOCUMENTO (ID_PESSOA, ID_DOCUMENTO) VALUES (1, 3);

SELECT PESSOA.NOME AS PESSOA, TIPO_DOCUMENTO.SIGLA AS DOCUMENTO, DOCUMENTO.NUMERO
FROM TB_DOCUMENTO DOCUMENTO
JOIN TB_PESSOA_DOCUMENTO PESSOA_DOCUMENTO ON PESSOA_DOCUMENTO.ID_DOCUMENTO = DOCUMENTO.CODIGO
JOIN TB_PESSOA PESSOA ON PESSOA.CODIGO = PESSOA_DOCUMENTO.ID_PESSOA
JOIN TB_TIPO_DOCUMENTO TIPO_DOCUMENTO ON TIPO_DOCUMENTO.CODIGO = DOCUMENTO.ID_TIPO_DOCUMENTO;