DROP TABLE IF EXISTS flyway_schema_history cascade;
DROP TABLE IF EXISTS TB_TIPO_PESSOA CASCADE;
DROP TABLE IF EXISTS TB_PESSOA CASCADE;
DROP TABLE IF EXISTS TB_TIPO_LANCAMENTO CASCADE;
DROP TABLE IF EXISTS TB_PRODUTO_SERVICO CASCADE;
DROP TABLE IF EXISTS TB_LANCAMENTO CASCADE;
DROP TABLE IF EXISTS TB_LANCAMENTO_PRODUTO_SERVICO CASCADE;
DROP TABLE IF EXISTS TB_CONTA_BANCARIA CASCADE;
DROP TABLE IF EXISTS TB_FORMA_PAGAMENTO CASCADE;
DROP TABLE IF EXISTS TB_PAGAMENTO CASCADE;
DROP TABLE IF EXISTS TB_PARCELAMENTO CASCADE;
DROP TABLE IF EXISTS TB_LANCAMENTO_PAGAMENTO CASCADE;
DROP TABLE IF EXISTS TB_TIPO_PESSOA CASCADE;
DROP TABLE IF EXISTS TB_ARQUIVO CASCADE;
DROP TABLE IF EXISTS TB_LANCAMENTO_ARQUIVO CASCADE;

-- FUNC0001 - GERENCIADOR DE PESSOAS

CREATE TABLE IF NOT EXISTS TB_TIPO_PESSOA (
    CODIGO SERIAL NOT NULL,
    DESCRICAO VARCHAR(85) NOT NULL,
    CONSTRAINT PK_TIPO_PESSOA PRIMARY KEY (CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_PESSOA (
    CODIGO SERIAL NOT NULL,
    ID_TIPO_PESSOA INTEGER not null,
    NOME VARCHAR(85) NOT NULL,
    CONSTRAINT PK_PESSOA PRIMARY KEY (CODIGO),
    CONSTRAINT FK_TIPO_PESSOA FOREIGN KEY (ID_TIPO_PESSOA) REFERENCES TB_TIPO_PESSOA (CODIGO)
);

-- FUNC0002 - GERENCIADOR DE LANCAMENTO FINANCEIRO

CREATE TABLE IF NOT EXISTS TB_TIPO_LANCAMENTO (
    CODIGO SERIAL NOT null,
    IDENTIFICADOR VARCHAR(85) NOT NULL,
    DESCRICAO VARCHAR(85) NOT NULL,
    CONSTRAINT PK_TIPO_LANCAMENTO PRIMARY KEY (CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_PRODUTO_SERVICO (
    CODIGO SERIAL NOT null,
    DESCRICAO VARCHAR(85) NOT NULL,
    CONSTRAINT PK_PRODUTO_SERVICO PRIMARY KEY (CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_LANCAMENTO (
    CODIGO SERIAL NOT NULL,
    ID_PESSOA_FAVORECIDA INTEGER NOT NULL,
    ID_PESSOA_RESPONSAVEL_LANCAMENTO INTEGER NOT NULL,
    ID_TIPO_LANCAMENTO INTEGER NOT NULL,
    IDENTIFICADOR VARCHAR(100) NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL,
    CONSTRAINT PK_LANCAMENTO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_PESSOA_FAVORECIDA FOREIGN KEY (ID_PESSOA_FAVORECIDA) REFERENCES TB_PESSOA(CODIGO),
    CONSTRAINT FK_PESSOA_RESPONSAVEL_LANCAMENTO FOREIGN KEY (ID_PESSOA_RESPONSAVEL_LANCAMENTO) REFERENCES TB_PESSOA(CODIGO),
    CONSTRAINT FK_TIPO_LANCAMENTO FOREIGN KEY (ID_TIPO_LANCAMENTO) REFERENCES TB_TIPO_LANCAMENTO(CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_LANCAMENTO_PRODUTO_SERVICO (
    CODIGO SERIAL NOT NULL,
    ID_LANCAMENTO INTEGER NOT NULL,
    ID_PRODUTO_SERVICO INTEGER NOT NULL,
    VALOR FLOAT NOT NULL,
    CONSTRAINT PK_LANCAMENTO_PRODUTO_SERVICO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_LANCAMENTO FOREIGN KEY (ID_LANCAMENTO) REFERENCES TB_LANCAMENTO(CODIGO),
    CONSTRAINT FK_PRODUTO_SERVICO FOREIGN KEY (ID_PRODUTO_SERVICO) REFERENCES TB_PRODUTO_SERVICO(CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_CONTA_BANCARIA (
    CODIGO SERIAL NOT NULL,
    ID_PESSOA_INSTITUICAO_FINANCEIRA INTEGER NOT NULL,
    ID_PESSOA_TITULAR INTEGER NOT NULL,
    NUMERO VARCHAR(80) NOT NULL,
    DATA_ABERTURA DATE NOT NULL,
    DATA_FECHAMENTO DATE NULL,
    SALDO FLOAT NOT NULL,
    CONSTRAINT PK_CONTA_BANCARIA PRIMARY KEY (CODIGO),
    CONSTRAINT FK_PESSOA_INSTITUICAO_FINANCEIRA FOREIGN KEY (ID_PESSOA_INSTITUICAO_FINANCEIRA) REFERENCES TB_PESSOA(CODIGO),
    CONSTRAINT FK_PESSOA_TITULAR FOREIGN KEY (ID_PESSOA_TITULAR) REFERENCES TB_PESSOA(CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_FORMA_PAGAMENTO (
    CODIGO SERIAL NOT NULL,
    DESCRICAO VARCHAR(85) NOT NULL,
    CONSTRAINT PK_FORMA_PAGAMENTO PRIMARY KEY (CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_PAGAMENTO (
    CODIGO SERIAL NOT NULL,
    ID_CONTA_BANCARIA INTEGER NOT NULL,
    ID_FORMA_PAGAMENTO INTEGER NOT NULL,
    DATA_PAGAMENTO DATE NOT NULL,
    CONSTRAINT PK_PAGAMENTO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_CONTA_BANCARIA FOREIGN KEY (ID_CONTA_BANCARIA) REFERENCES TB_CONTA_BANCARIA(CODIGO),
    CONSTRAINT FK_FORMA_PAGAMENTO FOREIGN KEY (ID_FORMA_PAGAMENTO) REFERENCES TB_FORMA_PAGAMENTO(CODIGO)
);


CREATE TABLE IF NOT EXISTS TB_LANCAMENTO_PAGAMENTO (
    CODIGO SERIAL NOT NULL,
    ID_LANCAMENTO INTEGER NOT NULL,
    ID_PAGAMENTO INTEGER NOT NULL,
    VALOR FLOAT NOT NULL,
    CONSTRAINT PK_LANCAMENTO_PAGAMENTO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_LANCAMENTO FOREIGN KEY (ID_LANCAMENTO) REFERENCES TB_LANCAMENTO(CODIGO),
    CONSTRAINT FK_PAGAMENTO FOREIGN KEY (ID_PAGAMENTO) REFERENCES TB_PAGAMENTO(CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_PARCELAMENTO (
    CODIGO SERIAL NOT NULL,
    ID_PAGAMENTO INTEGER NOT NULL,
    NUMERO INTEGER NOT NULL,
    VALOR FLOAT NOT NULL,
    CONSTRAINT PK_PARCELAMENTO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_PAGAMENTO FOREIGN KEY (ID_PAGAMENTO) REFERENCES TB_PAGAMENTO(CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_PAGAMENTO_PARCELAMENTO (
    CODIGO SERIAL NOT NULL,
    ID_PAGAMENTO INTEGER NOT NULL,
    ID_PARCELAMENTO INTEGER NOT NULL,
    CONSTRAINT PK_PAGAMENTO_PARCELAMENTO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_PAGAMENTO FOREIGN KEY (ID_PAGAMENTO) REFERENCES TB_PAGAMENTO(CODIGO),
    CONSTRAINT FK_PARCELAMENTO FOREIGN KEY (ID_PAGAMENTO) REFERENCES TB_PARCELAMENTO(CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_ARQUIVO (
    CODIGO SERIAL NOT NULL,
    NOME VARCHAR(45) NOT NULL,
    DESCRICAO VARCHAR(80) NULL,
    FORMATO VARCHAR(4) NOT NULL,
    CAMINHO VARCHAR(255) NULL,
    TAMANHO FLOAT NULL,
    DATA_CADASTRO DATE NOT NULL,
    DATA_ATUALIZACAO DATE NOT NULL,
    CONSTRAINT PK_ARQUIVO PRIMARY KEY (CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_LANCAMENTO_ARQUIVO (
    CODIGO SERIAL NOT NULL,
    ID_LANCAMENTO INTEGER NOT NULL,
    ID_ARQUIVO INTEGER NOT NULL,
    CONSTRAINT PK_LANCAMENTO_ARQUIVO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_LANCAMENTO FOREIGN KEY (ID_LANCAMENTO) REFERENCES TB_LANCAMENTO (CODIGO),
    CONSTRAINT FK_ARQUIVO FOREIGN KEY (ID_ARQUIVO) REFERENCES TB_ARQUIVO (CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_TIPO_PERMISSAO_PESSOA (
    CODIGO SERIAL NOT NULL,
    NOME VARCHAR(85) NOT NULL,
    CONSTRAINT PK_TIPO_PERMISSAO_PESSOA PRIMARY KEY (CODIGO)
);

CREATE TABLE IF NOT EXISTS TB_PERMISSAO_PESSOA (
    CODIGO SERIAL NOT NULL,
    ID_PESSOA INTEGER NOT NULL,
    ID_TIPO_PERMISSAO_PESSOA INTEGER NOT NULL,
    CONSTRAINT PK_PERMISSAO_PESSOA PRIMARY KEY (CODIGO),
    CONSTRAINT FK_ID_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA (CODIGO),
    CONSTRAINT FK_TIPO_PERMISSAO_PESSOA FOREIGN KEY (ID_TIPO_PERMISSAO_PESSOA) REFERENCES TB_TIPO_PERMISSAO_PESSOA (CODIGO)
);