-- DML
SELECT *
FROM TB_LANCAMENTO LANCAMENTO
JOIN TB_LANCAMENTO_PRODUTO_SERVICO LANCAMENTO_PRODUTO_SERVICO ON LANCAMENTO_PRODUTO_SERVICO.ID_LANCAMENTO = LANCAMENTO.CODIGO
JOIN TB_LANCAMENTO_PAGAMENTO LANCAMENTO_PAGAMENTO ON LANCAMENTO_PAGAMENTO.ID_LANCAMENTO = LANCAMENTO.CODIGO;