CREATE TABLE IF NOT EXISTS TB_PESSOA (
    CODIGO SERIAL NOT NULL,
    ID_TIPO_PESSOA INTEGER not null,
    NOME VARCHAR(85) NOT NULL,
    CONSTRAINT PK_PESSOA PRIMARY KEY (CODIGO),
    CONSTRAINT FK_TIPO_PESSOA FOREIGN KEY (ID_TIPO_PESSOA) REFERENCES TB_TIPO_PESSOA (CODIGO)
);