CREATE TABLE IF NOT EXISTS TB_TIPO_LANCAMENTO (
    CODIGO SERIAL NOT NULL,
    IDENTIFICADOR VARCHAR(85) NOT NULL,
    DESCRICAO VARCHAR(85) NOT NULL,
    CONSTRAINT PK_TIPO_LANCAMENTO PRIMARY KEY (CODIGO)
);