CREATE TABLE IF NOT EXISTS TB_LANCAMENTO (
    CODIGO SERIAL NOT NULL,
    ID_PESSOA_FAVORECIDA INTEGER NOT NULL,
    ID_PESSOA_RESPONSAVEL_LANCAMENTO INTEGER NOT NULL,
    ID_TIPO_LANCAMENTO INTEGER NOT NULL,
    IDENTIFICADOR VARCHAR(100) NOT NULL,
    DATA_LANCAMENTO DATE NOT NULL,
    CONSTRAINT PK_LANCAMENTO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_PESSOA_FAVORECIDA FOREIGN KEY (ID_PESSOA_FAVORECIDA) REFERENCES TB_PESSOA(CODIGO),
    CONSTRAINT FK_PESSOA_RESPONSAVEL_LANCAMENTO FOREIGN KEY (ID_PESSOA_RESPONSAVEL_LANCAMENTO) REFERENCES TB_PESSOA(CODIGO),
    CONSTRAINT FK_TIPO_LANCAMENTO FOREIGN KEY (ID_TIPO_LANCAMENTO) REFERENCES TB_TIPO_LANCAMENTO(CODIGO)
);