CREATE TABLE IF NOT EXISTS TB_LANCAMENTO_PRODUTO_SERVICO (
    CODIGO SERIAL NOT NULL,
    ID_LANCAMENTO INTEGER NOT NULL,
    ID_PRODUTO_SERVICO INTEGER NOT NULL,
    VALOR FLOAT NOT NULL,
    CONSTRAINT PK_LANCAMENTO_PRODUTO_SERVICO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_LANCAMENTO FOREIGN KEY (ID_LANCAMENTO) REFERENCES TB_LANCAMENTO(CODIGO),
    CONSTRAINT FK_PRODUTO_SERVICO FOREIGN KEY (ID_PRODUTO_SERVICO) REFERENCES TB_PRODUTO_SERVICO(CODIGO)
);