CREATE TABLE IF NOT EXISTS TB_PAGAMENTO (
    CODIGO SERIAL NOT NULL,
    ID_CONTA_BANCARIA INTEGER NOT NULL,
    ID_FORMA_PAGAMENTO INTEGER NOT NULL,
    DATA_PAGAMENTO DATE NOT NULL,
    CONSTRAINT PK_PAGAMENTO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_CONTA_BANCARIA FOREIGN KEY (ID_CONTA_BANCARIA) REFERENCES TB_CONTA_BANCARIA(CODIGO),
    CONSTRAINT FK_FORMA_PAGAMENTO FOREIGN KEY (ID_FORMA_PAGAMENTO) REFERENCES TB_FORMA_PAGAMENTO(CODIGO)
);