CREATE TABLE IF NOT EXISTS TB_LANCAMENTO_PAGAMENTO (
    CODIGO SERIAL NOT NULL,
    ID_LANCAMENTO INTEGER NOT NULL,
    ID_PAGAMENTO INTEGER NOT NULL,
    VALOR FLOAT NOT NULL,
    CONSTRAINT PK_LANCAMENTO_PAGAMENTO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_LANCAMENTO FOREIGN KEY (ID_LANCAMENTO) REFERENCES TB_LANCAMENTO(CODIGO),
    CONSTRAINT FK_PAGAMENTO FOREIGN KEY (ID_PAGAMENTO) REFERENCES TB_PAGAMENTO(CODIGO)
);