CREATE TABLE IF NOT EXISTS TB_PARCELAMENTO (
    CODIGO SERIAL NOT NULL,
    ID_PAGAMENTO INTEGER NOT NULL,
    NUMERO INTEGER NOT NULL,
    VALOR FLOAT NOT NULL,
    CONSTRAINT PK_PARCELAMENTO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_PAGAMENTO FOREIGN KEY (ID_PAGAMENTO) REFERENCES TB_PAGAMENTO(CODIGO)
);