CREATE TABLE IF NOT EXISTS TB_ARQUIVO (
    CODIGO SERIAL NOT NULL,
    NOME VARCHAR(45) NOT NULL,
    DESCRICAO VARCHAR(80) NULL,
    FORMATO VARCHAR(40) NOT NULL,
    CAMINHO VARCHAR(255) NULL,
    TAMANHO FLOAT NULL,
    DATA_CADASTRO DATE NOT NULL,
    DATA_ATUALIZACAO DATE NOT NULL,
    CONSTRAINT PK_ARQUIVO PRIMARY KEY (CODIGO)
);