CREATE TABLE IF NOT EXISTS TB_LANCAMENTO_ARQUIVO (
    CODIGO SERIAL NOT NULL,
    ID_LANCAMENTO INTEGER NOT NULL,
    ID_ARQUIVO INTEGER NOT NULL,
    CONSTRAINT PK_LANCAMENTO_ARQUIVO PRIMARY KEY (CODIGO),
    CONSTRAINT FK_LANCAMENTO FOREIGN KEY (ID_LANCAMENTO) REFERENCES TB_LANCAMENTO (CODIGO),
    CONSTRAINT FK_ARQUIVO FOREIGN KEY (ID_ARQUIVO) REFERENCES TB_ARQUIVO (CODIGO)
);