INSERT INTO TB_TIPO_PERMISSAO_PESSOA (NOME) VALUES ('DIRETOR_FINANCEIRO');
INSERT INTO TB_TIPO_PERMISSAO_PESSOA (NOME) VALUES ('ADMINISTRADOR_FINANCEIRO');
INSERT INTO TB_TIPO_PERMISSAO_PESSOA (NOME) VALUES ('CONSULTOR_FINANCEIRO');