INSERT INTO TB_PAPEL (NOME) VALUES ('DIRETOR_FINANCEIRO');
INSERT INTO TB_PAPEL (NOME) VALUES ('ADMINISTRADOR_FINANCEIRO');
INSERT INTO TB_PAPEL (NOME) VALUES ('CONSULTOR_FINANCEIRO');
INSERT INTO TB_PAPEL (NOME) VALUES ('USUARIO_SISTEMA');