CREATE TABLE IF NOT EXISTS TB_PERMISSAO_PESSOA (
    CODIGO SERIAL NOT NULL,
    ID_PESSOA INTEGER NOT NULL,
    ID_TIPO_PERMISSAO_PESSOA INTEGER NOT NULL,
    CONSTRAINT PK_PERMISSAO_PESSOA PRIMARY KEY (CODIGO),
    CONSTRAINT FK_ID_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA (CODIGO),
    CONSTRAINT FK_TIPO_PERMISSAO_PESSOA FOREIGN KEY (ID_TIPO_PERMISSAO_PESSOA) REFERENCES TB_TIPO_PERMISSAO_PESSOA (CODIGO)
);