CREATE TABLE IF NOT EXISTS TB_PESSOA_DOCUMENTO (
	CODIGO SERIAL NOT NULL,
	ID_PESSOA INTEGER NOT NULL,
	ID_DOCUMENTO INTEGER NOT NULL,
	CONSTRAINT PK_PESSOA_DOCUMENTO PRIMARY KEY (CODIGO),
	CONSTRAINT FK_PESSOA FOREIGN KEY (ID_PESSOA) REFERENCES TB_PESSOA (CODIGO),
	CONSTRAINT FK_DOCUMENTO FOREIGN KEY (ID_DOCUMENTO) REFERENCES TB_DOCUMENTO (CODIGO)
);