CREATE TABLE IF NOT EXISTS TB_ARQUIVO_DOCUMENTO (
	CODIGO SERIAL NOT NULL,
	ID_ARQUIVO INTEGER NOT NULL,
	ID_DOCUMENTO INTEGER NOT NULL,
	CONSTRAINT PK_ARQUIVO_DOCUMENTO PRIMARY KEY (CODIGO),
	CONSTRAINT FK_ARQUIVO FOREIGN KEY (ID_ARQUIVO) REFERENCES TB_ARQUIVO (CODIGO),
	CONSTRAINT FK_DOCUMENTO FOREIGN KEY (ID_DOCUMENTO) REFERENCES TB_DOCUMENTO (CODIGO)
);