INSERT INTO TB_TIPO_DOCUMENTO (SIGLA, DESCRICAO) VALUES ('CPF', '');
INSERT INTO TB_TIPO_DOCUMENTO (SIGLA, DESCRICAO) VALUES ('CNPJ', '');
INSERT INTO TB_TIPO_DOCUMENTO (SIGLA, DESCRICAO) VALUES ('RG', 'Registro Geral');